import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireFarmAccess } from "@/lib/access";
import { prisma } from "@/lib/prisma";
import { audit } from "@/lib/audit";
import { apiError } from "@/lib/api";
const schema=z.object({name:z.string().min(1).max(120).optional(),area:z.coerce.number().positive().optional(),latitude:z.coerce.number().gte(-90).lte(90).optional(),longitude:z.coerce.number().gte(-180).lte(180).optional(),soilType:z.string().max(100).nullable().optional(),status:z.enum(["SETUP","ACTIVE","INACTIVE","ARCHIVED"]).optional(),irrigation:z.array(z.object({type:z.enum(["Drip","Rain Pipe","Sprinkler","Flood","Other"]),details:z.string().max(300).optional().nullable()})).min(1).optional().superRefine((arr,ctx)=>{if(!arr) return; if(new Set(arr.map(x=>x.type)).size!==arr.length) ctx.addIssue({code:"custom",message:"Irrigation types must be unique.",path:["irrigation"]}); for(const it of arr) if(it.type==="Other" && !it.details?.trim()) ctx.addIssue({code:"custom",message:"Details are required for Other irrigation type.",path:["irrigation"]});})});
export async function GET(_:NextRequest,{params}:{params:Promise<{plotId:string}>}){try{const {plotId}=await params;const plot=await prisma.plot.findUniqueOrThrow({where:{id:plotId},include:{irrigation:true,cropCycles:{include:{varieties:true,milestones:true}},farm:{select:{id:true,name:true}}}});await requireFarmAccess(plot.farmId);return NextResponse.json(plot);}catch(error){return apiError(error);}}
export async function PATCH(request:NextRequest,{params}:{params:Promise<{plotId:string}>}) {try {const {plotId}=await params;const existing=await prisma.plot.findUniqueOrThrow({where:{id:plotId},include:{farm:{select:{totalArea:true,cultivableArea:true}}}});const actor=await requireFarmAccess(existing.farmId,true);const input=schema.parse(await request.json());if(existing.status==="ARCHIVED")throw new Error("An archived plot cannot be edited.");const area=input.area??Number(existing.area);const allocated=await prisma.plot.aggregate({where:{farmId:existing.farmId,deletedAt:null,id:{not:plotId}},_sum:{area:true}});if(Number(allocated._sum.area??0)+area>Number(existing.farm.cultivableArea))throw new Error("Total plot area cannot exceed the farm's cultivable area.");if(input.status==="ARCHIVED"){const active=await prisma.cropCycle.count({where:{plotId,status:{in:["PLANNED","ACTIVE"]}}});if(active)return NextResponse.json({error:"A plot with active/planned crop cycles cannot be archived."},{status:409});}const plot=await prisma.$transaction(async tx=>{if(input.irrigation){await tx.irrigationConfiguration.deleteMany({where:{plotId}});await tx.irrigationConfiguration.createMany({data:input.irrigation.map(v=>({plotId,...v}))});}const {irrigation,...data}=input;return tx.plot.update({where:{id:plotId},data,include:{irrigation:true}});});await audit(actor.id,"UPDATE","Plot",plotId,input);return NextResponse.json(plot);}catch(error){return apiError(error);}}
export async function DELETE(_:NextRequest,{params}:{params:Promise<{plotId:string}>}) {try {const {plotId}=await params;const plot=await prisma.plot.findUniqueOrThrow({where:{id:plotId}});const actor=await requireFarmAccess(plot.farmId,true);const active=await prisma.cropCycle.count({where:{plotId,status:{in:["PLANNED","ACTIVE"]}}});if(active) return NextResponse.json({error:"A plot with active/planned crop cycles cannot be archived."},{status:409});await prisma.plot.update({where:{id:plotId},data:{status:"ARCHIVED",deletedAt:new Date()}});await audit(actor.id,"ARCHIVE","Plot",plotId);return new NextResponse(null,{status:204});}catch(error){return apiError(error);}}
