import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireFarmAccess } from "@/lib/access";
import { prisma } from "@/lib/prisma";
import { audit } from "@/lib/audit";
import { calculatedInfrastructure, milestoneTemplates } from "@/lib/business";
import { apiError } from "@/lib/api";
const date=z.coerce.date();
const milestoneInput=z.object({name:z.string().min(2).max(120),targetDate:date,remarks:z.string().max(500).optional().nullable()});
const schema=z.object({cropName:z.string().min(2).max(120),startDate:date,expectedFirstHarvestDate:date.optional().nullable(),establishmentType:z.enum(["NURSERY_TRANSPLANTATION","DIRECT_SOWING"]),varieties:z.array(z.string().trim().min(1).max(80)).min(1).max(20),bedPreparationEnabled:z.boolean(),bedWidthCm:z.coerce.number().positive().optional().nullable(),bedCenterDistanceCm:z.coerce.number().positive().optional().nullable(),expectedBedsPerAcre:z.coerce.number().positive().optional().nullable(),mulchEnabled:z.boolean(),mulchHolePattern:z.enum(["SINGLE_LINE","DOUBLE_LINE_ZIGZAG"]).optional().nullable(),plantDistanceCm:z.coerce.number().positive().optional().nullable(),expectedPlantsPerAcre:z.coerce.number().positive().optional().nullable(),milestones:z.array(milestoneInput).min(3),supportActivities:z.array(milestoneInput).max(10).default([])}).superRefine((v,ctx)=>{if(v.bedPreparationEnabled&&!v.expectedBedsPerAcre)ctx.addIssue({code:"custom",path:["expectedBedsPerAcre"],message:"Expected beds per acre is required when bed preparation is enabled."});if(v.mulchEnabled&&(!v.mulchHolePattern||!v.plantDistanceCm))ctx.addIssue({code:"custom",path:["mulchHolePattern"],message:"Mulch pattern and plant distance are required when mulching is enabled."});});
export async function POST(request:NextRequest,{params}:{params:Promise<{plotId:string}>}){try{const {plotId}=await params;const plot=await prisma.plot.findUniqueOrThrow({where:{id:plotId}});const actor=await requireFarmAccess(plot.farmId,true);if(plot.status==="ARCHIVED")throw new Error("An archived plot cannot receive crop cycles.");const input=schema.parse(await request.json());const calc=calculatedInfrastructure(Number(plot.area),input.expectedBedsPerAcre,input.expectedPlantsPerAcre);const defaultNames=milestoneTemplates(input).map(m=>m.name);if(!defaultNames.every(name=>input.milestones.some(m=>m.name===name)))throw new Error("All four standard milestones are required.");const milestones=[...input.milestones,...input.supportActivities];const cycle=await prisma.$transaction(async tx=>{const created=await tx.cropCycle.create({data:{plotId,cropName:input.cropName,startDate:input.startDate,expectedFirstHarvestDate:input.expectedFirstHarvestDate,establishmentType:input.establishmentType,bedPreparationEnabled:input.bedPreparationEnabled,bedWidthCm:input.bedWidthCm,bedCenterDistanceCm:input.bedCenterDistanceCm,expectedBedsPerAcre:input.expectedBedsPerAcre,expectedTotalBeds:calc.expectedTotalBeds,mulchEnabled:input.mulchEnabled,mulchHolePattern:input.mulchHolePattern,plantDistanceCm:input.plantDistanceCm,expectedPlantsPerAcre:input.expectedPlantsPerAcre,expectedPlants:calc.expectedPlants,varieties:{create:[...new Set(input.varieties)].map(name=>({name}))},milestones:{create:milestones}} ,include:{milestones:true}});await tx.task.createMany({data:created.milestones.map(m=>({farmId:plot.farmId,plotId,cropCycleId:created.id,milestoneId:m.id,origin:"SYSTEM",category:"MILESTONE",title:m.name,description:`Complete the ${m.name} milestone.`,dueDate:m.targetDate,status:"AVAILABLE",createdById:actor.id}))});return created;});await audit(actor.id,"CREATE","CropCycle",cycle.id,{plotId,cropName:cycle.cropName,milestoneCount:cycle.milestones.length});return NextResponse.json(cycle,{status:201});}catch(error){return apiError(error);}}
