import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { currentActor, requireFarmAccess } from "@/lib/access";
import { prisma } from "@/lib/prisma";
import { audit } from "@/lib/audit";
import { apiError } from "@/lib/api";
const schema=z.object({userId:z.string().min(1),canManage:z.boolean().default(false)});
export async function GET(_:NextRequest,{params}:{params:Promise<{farmId:string}>}){try{const {farmId}=await params;await requireFarmAccess(farmId);const [access,users]=await Promise.all([prisma.farmAccess.findMany({where:{farmId},include:{user:{select:{id:true,name:true,email:true,role:true,active:true}}}}),prisma.user.findMany({where:{role:"FARM_OFFICER",active:true},select:{id:true,name:true,email:true,role:true},orderBy:{name:"asc"}})]);return NextResponse.json({access,users});}catch(error){return apiError(error);}}
export async function POST(request:NextRequest,{params}:{params:Promise<{farmId:string}>}){try{const {farmId}=await params;const actor=await requireFarmAccess(farmId,true);if(!["SUPER_ADMIN","FARM_ADMIN"].includes(actor.role))throw new Error("Only Farm Admins or Super Admins can assign farm officers.");const farm=await prisma.farm.findUniqueOrThrow({where:{id:farmId},select:{status:true}});if(farm.status!=="ACTIVE")throw new Error("Farm officers can only be assigned after farm activation.");const input=schema.parse(await request.json());const target=await prisma.user.findUniqueOrThrow({where:{id:input.userId},select:{role:true,active:true}});if(target.role!=="FARM_OFFICER"||!target.active)throw new Error("Only active Farm Officer accounts can be assigned.");const result=await prisma.$transaction(async tx=>{const access=await tx.farmAccess.upsert({where:{userId_farmId:{userId:input.userId,farmId}},update:{canManage:false},create:{userId:input.userId,farmId,canManage:false}});await tx.task.updateMany({where:{farmId,assignedOfficerId:null,origin:"SYSTEM",status:"AVAILABLE"},data:{assignedOfficerId:input.userId,status:"ASSIGNED"}});return access;});await audit(actor.id,"ASSIGN_FARM_OFFICER","FarmAccess",result.id,{farmId,userId:input.userId});return NextResponse.json(result,{status:201});}catch(error){return apiError(error);}}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{farmId:string}>}){try{const {farmId}=await params;const actor=await requireFarmAccess(farmId,true);if(!["SUPER_ADMIN","FARM_ADMIN"].includes(actor.role))throw new Error("Only Farm Admins or Super Admins can remove farm officers.");const {userId}=schema.pick({userId:true}).parse(await request.json());const target=await prisma.user.findUniqueOrThrow({where:{id:userId},select:{role:true}});if(target.role!=="FARM_OFFICER")throw new Error("Only Farm Officer assignments can be removed here.");await prisma.farmAccess.delete({where:{userId_farmId:{userId,farmId}}});await audit(actor.id,"UNASSIGN_FARM_OFFICER","FarmAccess",farmId,{farmId,userId});return new NextResponse(null,{status:204});}catch(error){return apiError(error);}}
